### ISSUE TITLE
[BUG] won't run if you have yarn installed

### ISSUE THREAD

**Issue by filipef101** [svbutko/react-native-template-strong#70]
**Describe the bug**
Why lock yarn out? There should be no need to
The problem ends up that if you do have installed you get the error about using rpm instead even when you run with npm/npx

**To Reproduce**
Have yarn installed, try to run the app

**Expected behavior**
should work

**Proposed solutionr**
Remove the yarn from the engines key on package.json

**Comment by svbutko** [comment]
I described it here:
https://svbutko.github.io/react-native-template-strong/faq#why-npm-and-not-yarn

Yarn is stale (v1) and not there are differences between v1 and v2 and not everybody uses it.
While NPM moves forward and getting better.

It's locked this way to make users stick to a single package manager, since when having two is incorrect and can lead to potential issues with dependencies.

If you'd like to stick with yarn you can remove these lines from `package.json`:

```
"engines": {
    "npm": ">= 6.14.13",
    "yarn": "Please use npm >= 6.14.13"
  }
 ```
 
I'm not against Yarn it's just got complicated with versioning and it's not healthy, so I'd rather lock it to NPM for users.

**Comment by filipef101** [comment]
You just have to remove from the template package json 
`    "yarn": "Please use npm >= 6.14.13"`
Because If I have yarn installed, like for other projects or whatever reason, if I run npm install, it sees that I have yarn installed globally and fails!
I wonder if its a bad idea to also remove the package lock, allowing users to use whatever they prefer, yarn or npm
